### ISSUE TITLE
Thinking Thread

### ISSUE THREAD

**Issue by Caerind** [Cmdu76/Delmia#1]
I open this issue to think about the global (and main) features of the game with my team-mates.

**Comment by ghost** [comment]
Now that debugging informations are available for GameStat sometimes mouse action produce two unit, don't seems to happen with buildings

**Comment by Caerind** [comment]
No it doesn't, if you look at the log you added, only one unit is created and also if you look at the Debug Info only one actor is added each click. You might have looked the "tickables" and that's because an Unit has itself and his SpriteComponent as Tickable. I should have explained it to you sorry...One more thing is that the action is based on event, so it only append on the mouse being pressed (not while it's pressed).

Got just few questions on your last commit : 
- Were you on Linux ?
- Did you success compile it with the template functions on the .cpp ? Because I thought template functions can only be on .hpp or specials includes files but not cpp.
- Not a question but tip, next time, use https://github.com/Cmdu76/Delmia/blob/master/src/NodeEngine/Utils/Log.hpp for "better" logging system

**Comment by ghost** [comment]
I was on Windows but in fact it doesn't happen any more, and I moved template in hpp sorry for that.
There is still bugs like:
- components can't be deleted in Nworld (crash) (already been discussed).
- I had difficulties in obtaining all position (tile used) by each sprite of a building.
