### ISSUE TITLE
Map generation

### ISSUE THREAD

**Issue by Caerind** [Cmdu76/Delmia#14]
Maybe we can simply this to our needs : https://github.com/simongeilfus/SimplexNoise

But at the moment, we can also do something simpler

**Comment by Cmdu76** [comment]
Maybe we can simply this to our needs : https://github.com/simongeilfus/SimplexNoise

But at the moment, we can also do something simpler

**Comment by Caerind** [comment]
All "tasks" can be found on Trello with this link : https://trello.com/b/DFSmrCfx/delmia
